AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
  RunRailsCops: true
Documentation:
  Enabled: false
LineLength:
  Max: 120
