before_install:
- echo '--colour' > ~/.rspec
- 'echo ''gem: --no-document'' > ~/.gemrc'
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- psql -c 'create database "mpd-sl_test";' -U postgres
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:migrate RAILS_ENV=test
script:
- bundle exec rake
- bundle exec rubocop -R --fail-level error
cache:
- bundler
language:
- ruby
notifications:
  email:
  - false
rvm:
- 2.1.2
addons:
  postgresql: '9.3'
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: wotvZOHJIyxRpKwXmC6Ox++pGQWFT0dxA3t+QwxGkjslTdLyHOVra5Cy8JVyZmyib1pBk4pSS3zk4kpZy79eH8oAxR/+BAiPeUvhGQOuXggRenA2hfthAqcrfJnIHrYXJSMX65UaiMXaDixcKQ2IStNiBQC6HXsvRD+UBOFagbc=
  app:
    master: mpd-sl-staging
    production: mpd-sl-production
  run:
  - rake db:migrate
  - restart
  - rake cleanup
  on:
    repo: slnz/mpd_tool
