source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'coffee-rails'
gem 'delayed_job_active_record'
gem 'email_validator'
gem 'flutie'
gem 'i18n-tasks'
gem 'jquery-rails'
gem 'normalize-rails'
gem 'pg'
gem 'rack-timeout'
gem 'recipient_interceptor'
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'simple_form'
gem 'enum_help'
gem 'title'
gem 'uglifier'
gem 'puma'
gem 'devise'
gem 'omniauth-facebook'
gem 'haml'
gem 'font-awesome-rails'
gem 'rest-client'
gem 'activeadmin', github: 'activeadmin'
gem 'active_admin_import' , github: 'activeadmin-plugins/active_admin_import'
gem 'active_skin'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'ransack'
gem 'has_scope'
gem 'friendly_id', '~> 5.1.0'
gem 'activemerchant'
gem 'active_type'
gem 'draper'
gem 'breadcrumbs_on_rails'
gem 'pxpay'
group :development do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-rubocop'
  gem 'guard-rails'
  gem 'guard-bundler'
  gem 'guard-puma'
  gem 'travis'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'letter_opener_web'
  gem 'thor'
end

group :development, :test do
  gem 'awesome_print'
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'faker'
end

group :test do
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'formulaic'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'vcr'
  gem 'webmock'
  gem 'timecop'
  gem 'fuubar'
end

group :staging, :production do
  gem 'rails_12factor'
  gem 'airbrake'
  gem 'newrelic_rpm'
  gem 'intercom-rails'
end
