# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.3.4'

gem 'active_admin_import', git: 'https://github.com/activeadmin-plugins/active_admin_import.git'
gem 'active_skin'
gem 'active_type'
gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin.git'
gem 'activemerchant'
gem 'bootstrap-sass'
gem 'breadcrumbs_on_rails'
gem 'coffee-rails'
gem 'delayed_job_active_record'
gem 'devise'
gem 'draper'
gem 'email_validator'
gem 'enum_help'
gem 'flutie'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'haml'
gem 'has_scope'
gem 'i18n-tasks'
gem 'jquery-rails'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'normalize-rails'
gem 'oj', '~> 2.12.14'
gem 'omniauth-facebook'
gem 'pg'
gem 'puma'
gem 'pxpay'
gem 'rack-timeout'
gem 'rails', '4.2.9'
gem 'ransack'
gem 'recipient_interceptor'
gem 'rest-client'
gem 'rollbar'
gem 'sass-rails'
gem 'simple_form'
gem 'title'
gem 'twitter-typeahead-rails'
gem 'uglifier'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-puma'
  gem 'guard-rails'
  gem 'guard-rspec', require: false
  gem 'guard-rubocop'
  gem 'letter_opener'
  gem 'letter_opener_web'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'thor'
  gem 'travis'
end

group :development, :test do
  gem 'awesome_print'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rubocop'
end

group :test do
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'formulaic'
  gem 'fuubar'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end

group :staging, :production do
  gem 'intercom-rails'
  gem 'newrelic_rpm'
  gem 'rails_12factor'
end
